### ISSUE TITLE
nothing happens when you click Connect (activateBrowserWallet) if you don't have any wallet installed

### ISSUE THREAD

**Issue by dzienisz** [EthWorks/useDApp#229]
there should be some kind of error handling like popup that you should inform you to install a wallet to use DApp

**Comment by marekkirejczyk** [comment]
Try: 
```ts
const {error} = useEthers() 
```
We will add info to docs.

**Comment by marekkirejczyk** [comment]
That will actually not work. Will develop solution soon.

**Comment by Szymx95** [comment]
Ok i read some web3React code and it turns out activate (which activateBrowserWallet uses) handles errors in 3 ways [read here](https://github.com/NoahZinsmeister/web3-react/tree/6737868693adb7e1e28ae80499e19901e9aae45a/docs#understanding-error-bubbling).

In short error should be available in `const { error } = useEthers()` but because useDApp defaults to read only connector the error is suppressed and is available only for few frames.

 So for now error can be handled for example in this way
```ts
  const {error} = useEthers()
  useEffect(() => {
    if(error){
      alert(error?.message)
    }
  }, [error])
```

In PR we will add way for error to be handled the same way as its handled in web3React so as a callback and throwing on error

**Comment by marekkirejczyk** [comment]
Release in @0.3.20,
Docs available here:
https://usedapp.readthedocs.io/en/latest/guide.html#handling-wallet-activation-errrors
