### ISSUE TITLE
Using with Typechain

### ISSUE THREAD

**Issue by jongold** [EthWorks/useDApp#325]
Hey! This project is so great!

Wondering if anyone had any suggestions of how to use it in conjunction with typechain - would be so sweet to have useContractCall / useContractFunction typed :)

Thank you!

**Comment by anthonymartin** [comment]
You could wrap useDapp hooks with something like this:
```` 
 function useContractFunction<ContractType extends Contract, Key extends keyof ContractType['functions']>(contract: ContractType, functionName:  Key) {
  }
  ```

**Comment by jongold** [comment]
Thank you!

**Comment by anthonymartin** [comment]
Hey @jongold - so we happened to be trying to implement this when you asked the question so it was good timing. It turns out it's slightly more complex to implement, and we're about 90% there, but we're missing just one part - that's getting the correct typed params for the `send()` function that's returned by the useDapp hook.

There's an issue about it here with our implementation so far: https://github.com/EthWorks/useDApp/issues/328

**Comment by anthonymartin** [comment]
Actually, I found the issue - here's working code for a hook wrapper that you could use with typechain:

```
import {
  TransactionStatus,
  useContractFunction as useDappUseContractFunction,
} from '@usedapp/core';
import { Contract } from 'ethers';

interface UseContractFunctionReturnType<
  ContractType extends Contract,
  Key extends keyof ContractType['functions'],
  Args extends Parameters<ContractType['functions'][Key]>,
> {
  send: (...args: Args) => Promise<void>;
  state: TransactionStatus;
}

function useContractFunction<
  ContractType extends Contract,
  Key extends keyof ContractType['functions'],
  Args extends Parameters<ContractType['functions'][Key]>,
>(
  contract: ContractType,
  functionName: Key,
): UseContractFunctionReturnType<ContractType, Key, Args> {
  const { send, state } = useDappUseContractFunction(
    contract,
    functionName as string,
  );
  return { send: (...args: Args) => send(...args), state };
}

export { useContractFunction };
```
