### ISSUE TITLE
How to prevent auto login?

### ISSUE THREAD

**Issue by cryptodapp** [EthWorks/useDApp#369]
Even when I deactivate, if metamask is logged in. The website automatically connects to metamask or trust wallet. Is there a way to clear this cache after running deactivate?

**Comment by tt-marek** [comment]
Merged and published!

**Comment by vm06007** [comment]
in latest version due to this, when you first land on the page it always prompts metaMask to connect and popup with MM appears. Is there any solution to keep auto-connect if user previously allowed access to metaMask, but not spam them with a popup from metaMask when they land on the page for the first time? Similar how it used to be in useDapp/core 0.9.0 this behavior seems to change in 0.10.0 @tt-marek
